name: Helo World Workflow

on:
 push:
  branches:
   - master
 pull_request:
  branches:
   - master
 workflow_dispach:

jobs:
 hello:
  runs_on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: hello word
   - run: echo "Hello World!"
   - shell: bash

goodbay:
 runs-on: ubuntu-latest
 steps:
  - name: goodby world
    run: echo "Goodbye World!"
    shell: bash
